let labReport=null,labDetail=null,labPollTimer=null,portfolioRequest=0;
const labForm=document.getElementById('labForm');
function labSettings(){const s={};for(const e of labForm.elements){if(!e.name)continue;s[e.name]=e.dataset.list?e.value.split(/[,，\s]+/).filter(Boolean).map(Number):e.type==='number'||e.name==='weightStep'?Number(e.value):e.value;}s.timeframes=[...document.querySelectorAll('[data-period]:checked')].map(e=>e.value);return s;}
function labEstimate(){const s=labSettings();$('labEstimate').textContent=num(s.timeframes.length*s.drawdowns.length*s.takeProfits.length*(s.liquidationDrops.length+1));}
function setLabSettings(s){for(const e of labForm.elements){if(!e.name||!(e.name in s))continue;e.value=Array.isArray(s[e.name])?s[e.name].join(','):s[e.name];}for(const e of document.querySelectorAll('[data-period]'))e.checked=s.timeframes.includes(e.value);labEstimate();}
function labMessage(text,bad=false){$('labMessage').textContent=text;$('labMessage').className=bad?'error':'micro';}
async function refreshLabSources(){const previous=$('labSource').value;const rows=(await api('/api/runs')).filter(r=>r.timeframe==='5m'&&r.AuditCoverage?.EligibleForAllocation===true&&Date.parse(r.end)-Date.parse(r.start)>=89*86400000);$('labSource').innerHTML=rows.map(r=>`<option value="${esc(r.id)}">${esc(r.start)} — ${esc(r.end)} · ${num(r.models)} 模型 · ${esc(r.id.slice(-6))}</option>`).join('');const preferred=previous||labReport?.SourceRun||runId;if(rows.some(r=>r.id===preferred))$('labSource').value=preferred;}
function studioTab(id){for(const p of document.querySelectorAll('[data-pane]'))p.hidden=p.dataset.pane!==id;for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===id);b.setAttribute('aria-selected',String(b.dataset.tab===id));b.tabIndex=b.dataset.tab===id?0:-1;}history.replaceState(null,'','#'+id);if(id==='lab')refreshLabSources().catch(e=>labMessage(e.message,true));}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>studioTab(b.dataset.tab);
labForm.addEventListener('input',labEstimate);labForm.addEventListener('change',labEstimate);
labForm.onsubmit=async e=>{e.preventDefault();$('labStart').disabled=true;labMessage('正在创建周期与资金配比实验…');try{const r=await api('/api/lab/start',{source:$('labSource').value,settings:labSettings()});localStorage.setItem('btcLabJob',r.id);pollLab(r.id);}catch(ex){labMessage(ex.message,true);$('labStart').disabled=true;}};
async function pollLab(id){try{const s=await api('/api/lab/status?id='+encodeURIComponent(id));$('labProgress').hidden=false;$('labProgress').value=s.total?100*s.completed/s.total:0;labMessage(s.message||'准备中');$('labStart').disabled=true;if(s.status==='RUNNING'){labPollTimer=setTimeout(()=>pollLab(id),2000);}else{localStorage.removeItem('btcLabJob');if(s.status==='COMPLETE')await loadLab();else labMessage(s.message,true);}}catch(e){labMessage(e.message,true);$('labStart').disabled=true;localStorage.removeItem('btcLabJob');}}
async function loadLab(){const r=await api('/api/lab/latest');if(r.Status!=='COMPLETE'){return;}labReport=r;$('labResults').hidden=false;$('labEmpty').hidden=true;$('labResultMeta').innerHTML=[[r.CandidateCount,'基础策略'],[r.PoolCount,'入选策略'],[r.PortfolioCount,'资金配比'],[r.EligibleCount,'符合约束']].map(([v,label])=>`<div><strong>${num(v)}</strong><span>${label}</span></div>`).join('');
$('labCoverageWindow').textContent=`历史覆盖：${r.Config.StartDate.replace('T',' ').replace('Z','')} → ${r.Config.EndDate.replace('T',' ').replace('Z','')} · UTC，右端不含。连续资金曲线不在周期边界重置本金。`;
const audit=r.AuditCoverage,passed=audit?.Status==='PASS';$('labAuditCoverage').className=passed?'source-strip':'notice';$('labAuditCoverage').textContent=passed?'配比独立审计通过：候选曲线、全量资金配比、筛选排名与已保存指标已逐项复算，候选强平触发已独立核验。历史通过不代表未来安全。':'配比完整审计尚未通过；当前结果仅保留展示，不能据此认定策略安全。';$('labAuditDownload').hidden=!r.ComprehensiveAudit;$('labAuditDownload').href=`./lab-files/${r.ID}/comprehensive_audit.json`;$('labRiskAuditDownload').hidden=!audit?.Checks?.Liquidation?.File;$('labRiskAuditDownload').href=`./lab-files/${r.ID}/independent_risk_audit.json`;const checked=r.SourceRecheck;$('labProvenance').textContent=`行情来源：币安官方 BTCUSDT · 5m · ${r.Config.StartDate} 至 ${r.Config.EndDate}。${sourceRecheckText(checked)}收益与风险为本地计算；资金费结算价代理见数据核验。`;
$('labScope').textContent=`已完成实验：周期 ${r.Settings.timeframes.join(' / ')}；训练 / 验证回撤上限 ${r.Settings.maxDrawdown}%（日末），永续 ≤ ${r.Settings.maxFutureWeight}%，现金 ≥ ${r.Settings.minCashWeight}%。配比按独立资金份额计算，保留现金不自动补充永续保证金，不代表同一全仓账户共享抵押品的清算模拟。上方修改参数后需重新运行才会更新此结果。`;
$('labSegmentDates').innerHTML=Object.entries(r.Segments).map(([k,v])=>`<div><span>${({Train:'训练 · 选参数',Validation:'验证 · 选配比',Test:'保留 · 只检验'})[k]}</span><strong>${v.StartUTC.slice(0,10)} → ${v.EndUTCExclusive.slice(0,10)}</strong><small>${v.Days} 个观察区间 · 右端不含</small></div>`).join('');
$('labMethods').innerHTML=r.Methods.map(v=>`<li>${esc(v)}</li>`).join('');$('labSelectionNote').textContent=r.SelectionLabel;
for(const [id,file] of [['labCandidatesCsv','candidates.csv'],['labPortfoliosCsv','portfolios.csv'],['labReportJson','report.json']])$(id).href=`./lab-files/${r.ID}/${file}`;
$('periodRows').innerHTML=r.Periods.map(p=>`<tr><td><b>${esc(p.Timeframe)}</b></td><td>${p.Market==='FUTURES'?'永续':'现货'}</td><td>${pct(p.DrawdownPct)} / ${pct(p.TakeProfitPct)}</td><td class="${valueTone(p.TrainReturnPct)}">${signedValue(p.TrainReturnPct)}</td><td class="${valueTone(p.ValidationReturnPct)}">${signedValue(p.ValidationReturnPct)}</td><td class="${valueTone(p.TestReturnPct)}">${signedValue(p.TestReturnPct)}</td><td class="tone-risk">${pct(p.FullDailyDrawdownPct)}</td></tr>`).join('');
$('portfolioRows').innerHTML=r.Portfolios.slice(0,30).map((p,i)=>`<tr><td>${i+1}</td><td><button data-portfolio="${p.PortfolioID}" class="portfolio-pick">${p.FutureWeight} / ${p.SpotWeight} / ${p.CashWeight}</button></td><td>${esc(candidateLabel(p.FutureID))}</td><td>${esc(candidateLabel(p.SpotID))}</td><td class="${valueTone(p.ValidationReturnPct)}">${signedValue(p.ValidationReturnPct)}</td><td class="tone-risk">${pct(p.ValidationDailyDrawdownPct)}</td><td class="tone-ratio">${num(p.ValidationScore)}</td><td class="${valueTone(p.Segments.Test?.ReturnPct)}">${signedValue(p.Segments.Test?.ReturnPct)}</td></tr>`).join('');
drawFrontier(r.Frontier);if(r.Portfolios.length){await selectPortfolio(r.Portfolios[0].PortfolioID);}else{$('portfolioDetail').hidden=true;$('labNoMatch').hidden=false;$('labNoMatch').textContent='当前约束下没有合格配比。可调整回撤上限、训练交易门槛或参数范围后再试；系统不会强行给出最优比例。';}}
function candidateLabel(id){const c=labReport?.Candidates.find(x=>x.StrategyID===id);return c?`${c.Timeframe} · 回撤 ${c.DrawdownPct}% / 止盈 ${c.TakeProfitPct}% · ${num(c.EffectiveLeverage)}×`:'未配置';}
async function selectPortfolio(id){const request=++portfolioRequest,d=await api(`/api/lab/portfolio?id=${labReport.ID}&portfolio=${id}`);if(request!==portfolioRequest)return;labDetail=d;$('portfolioDetail').hidden=false;$('labNoMatch').hidden=true;
const rank=labReport.Portfolios.findIndex(p=>p.PortfolioID===id)+1;$('portfolioTitle').textContent=`候选 ${rank} · 永续 ${d.FutureWeight}% / 现货 ${d.SpotWeight}% / 现金 ${d.CashWeight}%`;
$('portfolioComponents').textContent=`永续：${candidateLabel(d.FutureID)}；现货：${candidateLabel(d.SpotID)}`;
$('allocationBar').innerHTML=`<svg viewBox="0 0 100 8" preserveAspectRatio="none" role="img" aria-label="永续 ${d.FutureWeight}%，现货 ${d.SpotWeight}%，现金 ${d.CashWeight}%"><rect width="${d.FutureWeight}" height="8" fill="#087b57"/><rect x="${d.FutureWeight}" width="${d.SpotWeight}" height="8" fill="#8566cb"/><rect x="${d.FutureWeight+d.SpotWeight}" width="${d.CashWeight}" height="8" fill="#8997a9"/></svg><div class="allocation-legend"><span>● 永续 ${d.FutureWeight}%</span><span>● 现货 ${d.SpotWeight}%</span><span>● 现金 ${d.CashWeight}%</span></div>`;
renderHistoricalCycles(d);renderPortfolioMetrics();drawLabCurve();$('monthlyRows').innerHTML=d.Months.map(m=>`<div class="month-cell ${m.ReturnPct>=0?'positive':'negative'}"><small>${esc(m.Month)}</small><strong>${signedValue(m.ReturnPct)}</strong><span>${m.Days} 个观察区间</span></div>`).join('');
for(const b of document.querySelectorAll('[data-portfolio]'))b.classList.toggle('selected',b.dataset.portfolio===id);
}
function signedValue(v,u='%'){return v==null?'—':`${v>0?'+':''}${num(v)}${u}`;}
function valueTone(v){return v==null?'tone-neutral':v>0?'tone-positive':v<0?'tone-negative':'tone-neutral';}
function statCard(m,k,label,u,kind,help){const v=m?.[k],tone=kind==='signed'?valueTone(v):v==null?'tone-neutral':`tone-${kind}`;return `<div class="stat-tile ${tone}"><span>${label}</span><strong>${kind==='signed'?signedValue(v,u):v==null?'—':num(v)+u}</strong><small>${help}</small></div>`;}
function renderPortfolioMetrics(){if(!labDetail)return;const key=$('labMetricSegment').value,base=labDetail.Segments[key],m=base?{...base,...labDetail.Analytics?.[key]}:null;
const candidate=labReport.Candidates.find(c=>c.StrategyID===labDetail.FutureID),issues=[];if(m?.ReturnPct<0)issues.push(`当前统计区间亏损 ${pct(-m.ReturnPct)}`);if(m?.DailyMaxDrawdownPct>labReport.Settings.maxDrawdown)issues.push(`日末回撤 ${pct(m.DailyMaxDrawdownPct)}，已超过训练 / 验证筛选上限 ${labReport.Settings.maxDrawdown}%`);if(!m||!Number.isFinite(m.ReturnPct)||!Number.isFinite(m.DailyMaxDrawdownPct))issues.push('当前统计区间指标未完整定义，无法判断是否满足筛选条件');const liqs=candidate?.LiquidationCount||0;if(liqs)issues.push(`所选永续子策略在全程发生 ${liqs} 次强平`);$('portfolioRiskNote').className=issues.length?'error':'notice';$('portfolioRiskNote').textContent=(issues.length?issues.join('；')+'。':'当前统计区间收益非负，日末回撤未超过筛选上限。')+'筛选条件仅约束训练 / 验证段；保留段和全程可能亏损或超过回撤上限。日末回撤不代表盘中最大损失。现金独立保留，不自动补充永续保证金。';
const groups=[['核心表现',[
['ReturnPct','区间收益','%','signed','包含子策略交易费用与资金费'],['ExcessReturnPP','超额收益',' pp','signed','相对同期 BTC 买入持有，百分点'],['DailyMaxDrawdownPct','最大回撤 · 日末','%','risk','从区间历史净值高点计算'],['Sharpe','夏普比率','','ratio','每日收益，零无风险利率']]],
['收益质量',[
['CAGRPct','年化收益','%','signed','按 365.25 天折算，非收益预测'],['BenchmarkReturnPct','BTC 持有收益','%','signed','同一日期区间的现货基准'],['Sortino','Sortino 比率','','ratio','收益 / 下行偏差，目标收益为 0'],['Calmar','Calmar 比率','','ratio','年化收益 / 日末最大回撤']]],
['回撤与尾部风险',[
['CurrentDrawdownPct','期末仍处于回撤','%','risk','相对本统计区间的净值高点'],['RecoveryNeededPct','回到高点需上涨','%','risk','高点净值 / 期末净值 − 1'],['CurrentUnderwaterDays','本轮回撤已持续',' 天','risk','到期末尚未回到高点的天数'],['LongestUnderwaterDays','最长未回到高点',' 天','risk','日末净值连续低于历史高点'],['VaR95Pct','单日损失 VaR95','%','risk','历史日收益 5% 分位的损失'],['CVaR95Pct','尾部损失 CVaR95','%','risk','低于该分位的平均单日损失'],['UlcerIndex','回撤痛苦指数','','risk','日末回撤平方均值的平方根'],['DownsideVolatilityPct','年化下行波动','%','risk','仅负收益偏差，按全年日数折算']]],
['稳定性与基准关联',[
['PositiveDayPct','盈利日占比','%','ratio','收益 > 0 的日期 / 全部观测日'],['PositiveMonthPct','完整月份盈利占比','%','ratio',`${m?.CompleteMonths??0} 个完整自然月，排除首尾残月`],['MaxConsecutiveLosingDays','最长连续亏损',' 天','risk','零收益日会中断连续亏损'],['VolatilityPct','年化总波动','%','risk','日收益样本标准差 × √365.25'],['BestDayPct','最佳单日','%','signed','区间内单日最高净值收益'],['WorstDayPct','最差单日','%','signed','区间内单日最低净值收益'],['BestMonthPct','最佳完整月份','%','signed','只使用完整自然月'],['WorstMonthPct','最差完整月份','%','signed','只使用完整自然月'],['BenchmarkCorrelation','与 BTC 日收益相关性','','ratio','−1 至 1；任一序列恒定则不定义'],['Beta','相对 BTC 的 Beta','','ratio','协方差 / BTC 日收益方差'],['TrackingErrorPct','年化跟踪误差','%','risk','组合减基准的日收益差标准差'],['InformationRatio','信息比率','','ratio','日超额收益均值 / 跟踪偏差，年化']]],
['涨跌环境与收益分布',[
['PositiveDays','盈利观察区间',' 个','positive','按组合日净值收益 > 0 计数'],['NegativeDays','亏损观察区间',' 个','negative','按组合日净值收益 < 0 计数'],['FlatDays','净值持平区间',' 个','neutral','日收益恰好为 0，包含空仓日期'],['OutperformDaysPct','跑赢 BTC 的天数占比','%','ratio','组合日收益严格高于 BTC 的日期占比'],['UpDayParticipationPct','BTC 上涨日参与比','%','ratio','BTC 上涨日：组合平均收益 / BTC 平均收益'],['DownDayParticipationPct','BTC 下跌日参与比','%','risk','BTC 下跌日：组合平均收益 / BTC 平均收益；负值表示逆势盈利']]],
['滚动窗口表现',[
['WorstRolling30Pct','最差 30 天','%','signed','统计区间内所有完整滚动窗口'],['BestRolling30Pct','最佳 30 天','%','signed','观察数不足时显示 —'],['WorstRolling90Pct','最差 90 天','%','signed','统计区间内所有完整滚动窗口'],['BestRolling90Pct','最佳 90 天','%','signed','观察数不足时显示 —'],['WorstRolling180Pct','最差 180 天','%','signed','统计区间内所有完整滚动窗口'],['BestRolling180Pct','最佳 180 天','%','signed','观察数不足时显示 —'],['Rolling90PositivePct','90 天窗口盈利占比','%','ratio','滚动窗口相互重叠，不是独立样本']]]];
$('portfolioMetrics').innerHTML=groups[0][1].map(slot=>statCard(m,...slot)).join('');
$('portfolioMoreMetrics').innerHTML=groups.slice(1).map(([title,slots])=>`<section class="analytics-group"><h4>${title}</h4><div class="stats-grid">${slots.map(slot=>statCard(m,...slot)).join('')}</div></section>`).join('');
const segment=labReport.Segments[key];const interval=segment?`${segment.StartUTC.slice(0,10)} → ${segment.EndUTCExclusive.slice(0,10)}（不含右端） · `:'全部历史 · ';$('metricSegmentNote').textContent=m?`${interval}${m.Days} 个收益观察区间，首尾部分日 ${m.PartialEndpointIntervals||0} 个 · ${key==='Full'?'全程维持最初资金分配':'分段起点按目标比例重新归一化'} · 年化 365.25 天 · 无风险收益与目标收益 0。${key==='Test'?'保留段未用于排名。':''}`:'该分段起点子策略已归零，收益率与风险比率无法定义。';
$('labMetricsCsv').href=`/api/lab/export?id=${labReport.ID}&portfolio=${labDetail.PortfolioID}&kind=metrics&segment=${key}`;
$('benchmarkNote').textContent=labDetail.BenchmarkUnavailable?`基准暂不可用：${labDetail.BenchmarkUnavailable}`:labDetail.BenchmarkMethod;
}
function drawLabCurve(){if(!labDetail)return;$('labCurveCsv').href=`/api/lab/export?id=${labReport.ID}&portfolio=${labDetail.PortfolioID}&kind=curve&window=${$('labCurveWindow').value}`;const pts=labDetail.Points,range=Number($('labCurveWindow').value);const data=range?pts.slice(-range-1):pts;const benchmark=labDetail.BenchmarkPoints?.length===pts.length?(range?labDetail.BenchmarkPoints.slice(-range-1):labDetail.BenchmarkPoints):[];const values=[...data.map(p=>p[1]),...benchmark.map(p=>p[1])];const w=800,h=270,pad=62,max=Math.max(...values),min=Math.min(...values);const x=i=>pad+i/(data.length-1)*(w-pad-20),y=v=>h-38-(v-min)/(max-min||1)*(h-68);const path=data.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(p[1]).toFixed(2)}`).join(' ');const benchPath=benchmark.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(p[1]).toFixed(2)}`).join(' ');const date=t=>new Date(t).toISOString().slice(0,10);
$('labCurve').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="组合每日净值，${date(data[0][0])} 至 ${date(data.at(-1)[0])}"><defs><linearGradient id="curveFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#087b57" stop-opacity=".23"/><stop offset="100%" stop-color="#087b57" stop-opacity="0"/></linearGradient></defs>${[0,.5,1].map(v=>{const yy=y(min+(max-min)*v);return `<line x1="54" y1="${yy}" x2="780" y2="${yy}" stroke="#dce4ee"/><text x="48" y="${yy+4}" text-anchor="end" fill="#52657b" font-size="10">${num((min+(max-min)*v)/1000)}k</text>`;}).join('')}<path d="${path} L${x(data.length-1)},${h-38} L54,${h-38}Z" fill="url(#curveFill)"/><path d="${benchPath}" stroke="#7357bd" stroke-dasharray="5 4" stroke-width="1.8" fill="none"/><path d="${path}" stroke="#087b57" stroke-width="2" fill="none"/><text x="54" y="258" fill="#52657b" font-size="11">${date(data[0][0])}</text><text x="780" y="258" text-anchor="end" fill="#52657b" font-size="11">${date(data.at(-1)[0])}</text></svg>`;
const probe=$('labCurveProbe');probe.max=data.length-1;probe.value=data.length-1;
const showDay=i=>{i=Math.max(0,Math.min(data.length-1,Math.round(i)));const p=data[i];probe.value=i;$('labDayInfo').textContent=`${date(p[0])} UTC 估值时刻 · 净值 ${num(p[1])} USDT ${benchmark.length?`· BTC 持有 ${num(benchmark[i][1])} USDT `:""}· 相对全程日末高点回撤 ${pct(p[2])}`;};
probe.oninput=()=>showDay(Number(probe.value));$('labCurve').onpointermove=e=>{const box=$('labCurve').querySelector('svg').getBoundingClientRect();showDay(((e.clientX-box.left)/box.width*800-62)/718*(data.length-1));};showDay(data.length-1);
const periodReturn=(data.at(-1)[1]/data[0][1]-1)*100;$('curveWindowNote').textContent=`${date(data[0][0])} 至 ${date(data.at(-1)[0])} · ${num((data.at(-1)[0]-data[0][0])/86400000)} 天 · 窗口收益 ${pct(periodReturn)} · 期末 ${num(data.at(-1)[1])} USDT。原始全程固定初始配比曲线，未在窗口起点调仓。`;}
function drawFrontier(points){if(!points.length){$('frontier').textContent='没有可评估的配比';return;}const minY=Math.min(0,...points.map(p=>p.Return)),maxY=Math.max(...points.map(p=>p.Return),1),maxX=Math.max(...points.map(p=>p.Drawdown),1);const x=v=>52+v/maxX*700,y=v=>210-(v-minY)/(maxY-minY)*174;
$('frontier').innerHTML=`<svg viewBox="0 0 800 260" role="img" aria-label="验证段资金配比收益与日末回撤散点图"><line x1="52" y1="210" x2="752" y2="210" stroke="#bac9d8"/><line x1="52" y1="30" x2="52" y2="210" stroke="#bac9d8"/>${[0,.5,1].map(v=>`<text x="${x(v*maxX)}" y="229" text-anchor="middle" fill="#52657b" font-size="10">${num(v*maxX)}%</text><text x="46" y="${y(minY+v*(maxY-minY))+4}" text-anchor="end" fill="#52657b" font-size="10">${num(minY+v*(maxY-minY))}%</text>`).join('')}${points.map(p=>`<circle cx="${x(p.Drawdown)}" cy="${y(p.Return)}" r="3" fill="${p.Eligible?'#087b57':'#8794a6'}" opacity=".45"><title>${esc(p.ID)} · 回撤 ${pct(p.Drawdown)} · 收益 ${pct(p.Return)} · ${p.Eligible?'符合约束':'未通过约束'}</title></circle>`).join('')}<text x="400" y="252" text-anchor="middle" fill="#52657b" font-size="11">日末最大回撤 →</text><text x="56" y="20" fill="#52657b" font-size="11">区间收益</text></svg>`;}
function downloadLabCsv(name,text){const u=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('portfolioRows').onclick=e=>{const b=e.target.closest('[data-portfolio]');if(b)selectPortfolio(b.dataset.portfolio).catch(e=>labMessage(e.message,true));};$('labMetricSegment').onchange=renderPortfolioMetrics;$('labCurveWindow').onchange=drawLabCurve;
$('labReset').onclick=async()=>{setLabSettings(await api('/api/lab/defaults'));labMessage('已恢复实验默认参数；已有结果保留。');};
(async()=>{try{setLabSettings(await api('/api/lab/defaults'));await loadLab();if(labReport)setLabSettings(labReport.Settings);if(['lab','data','sim'].includes(location.hash.slice(1)))studioTab(location.hash.slice(1));const shared=await api('/api/lab/active');const active=shared.status==='RUNNING'?shared.id:localStorage.getItem('btcLabJob');if(active)pollLab(active);}catch(e){labMessage(e.message,true);}})();

for(const button of document.querySelectorAll('[data-controls-toggle]')){const aside=button.closest('aside');const set=open=>{aside.classList.toggle('controls-collapsed',!open);button.setAttribute('aria-expanded',String(open));button.textContent=open?'收起设置 ↑':'展开设置 ↓';};set(!matchMedia('(max-width:850px)').matches);button.onclick=()=>set(button.getAttribute('aria-expanded')!=='true');}

for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-tab]')];let i=tabs.indexOf(b);if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();studioTab(tabs[i].dataset.tab);tabs[i].focus();});

function renderHistoricalCycles(d){const rows=d.HistoricalCycles||[];const host=$('historicalCycleComparison');host.hidden=!rows.length;if(!rows.length)return;host.innerHTML='<h3>三个历史周期 · 连续持仓检验</h3><p class="micro">按精确 UTC 边界估值，继承全程持仓与最初配比；未在周期切换时清仓或调仓。此表仅检验，不参与排名。</p><table><thead><tr><th>周期 · UTC</th><th>期初净值</th><th>期末净值</th><th>周期收益</th></tr></thead><tbody>'+rows.map(c=>`<tr><td><b>${esc(c.Label)}</b><br><small>${esc(c.StartUTC.replace('T',' ').replace('Z',''))} → ${esc(c.EndUTCExclusive.replace('T',' ').replace('Z',''))}</small></td><td>${num(c.StartWealth)}</td><td>${num(c.EndWealth)}</td><td class="${valueTone(c.ReturnPct)}">${signedValue(c.ReturnPct)}</td></tr>`).join('')+'</tbody></table>';}

$('labStart').disabled=true;$('labStart').textContent='新配比扫描请使用本地版';$('labMessage').textContent='可浏览已发布的全部配比 CSV 与前 60 个保存候选；修改参数不会重算已有快照。';
